---
# Install nodejs if baserow_install_nodejs: true
# Primarily using geerlingguy/ansible-role-nodejs as inspiration
- name: Add nodesource apt key
  ansible.builtin.apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"
    state: present

- name: Add NodeSource repositories for Node.js.
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/node_{{baserow_nodejs_version}} {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_{{baserow_nodejs_version}} {{ ansible_distribution_release }} main"
  register: node_repo

- name: Update apt cache if repo was added.
  ansible.builtin.apt: update_cache=yes
  when: node_repo.changed
  tags: ['skip_ansible_lint']

- name: Ensure Node.js and npm are installed.
  ansible.builtin.apt:
    name: "nodejs={{ baserow_nodejs_version|regex_replace('x', '') }}*"
    state: present
