---
# Install yarn when baserow_install_yarn: true
# Inspiration from angristan/ansible-yarn
- name: Add Yarn apt key
  ansible.builtin.apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg

- name: Add Yarn repository
  ansible.builtin.apt_repository:
    repo: "deb https://dl.yarnpkg.com/debian/ stable main"
    filename: yarn

- name: Install Yarn
  ansible.builtin.apt:
    name: yarn
